name: First workflow in Node JS
on: 
  fork: 
    branches:  
      - express-training
jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout 
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.9.1
        with:
          node-version: '22.13.1'
      - run: |
          node -v
          npm -v
          npm install
